----------------------------------------------------
-- Count for total RA fields for each "Email"
----------------------------------------------------
select total_ra_ct, count("Email") 
from (
select  	"Email"
		,"RA - Agriculture" 														
		+"RA - Analytical Chemistry" 											
		+"RA - Anatomy" 															
		+"RA - Biochemistry" 													
		+"RA - Biodefense" 													
		+"RA - Bioinformatics"													
		+"RA - Biophysics" 														
		+"RA - Bioprocessing" 													
		+"RA - Biostatistics" 													
		+"RA - Botany" 													
		+"RA - Cancer/Oncology" 												
		+"RA - Cell Biology" 												
		+"RA - Clinical Diagnostics" 											
		+"RA - Developmental Biology" 										
		+"RA - Drug Discovery/R&D" 												
		+"RA - Environmental Science" 										
		+"RA - Epigenetics/Epigenomics" 										
		+"RA - Food Science" 												
		+"RA - Forensics" 													
		+"RA - Gene Therapy" 												
		+"RA - Genetics/Genomics" 											
		+"RA - Hematology" 														
		+"RA - Histology" 														
		+"RA - Immunology/Virology" 												
		+"RA - Material Sciences/Polymer Chemistry" 							
		+"RA - Medicinal Chemistry" 											
		+"RA - Microbiology" 												
		+"RA - Molecular Biology" 												
		+"RA - Molecular Diagnostics" 										
		+"RA - Nanotechnology" 												
		+"RA - Neuroscience" 												
		+"RA - Organic Chemistry" 											
		+"RA - Other (please specify)" 											
		+"RA - Pathology" 														
		+"RA - Pharmacogenomics" 												
		+"RA - Protein Sciences" 												
		+"RA - Proteomics" 														
		+"RA - Regenerative Medicine"											
		+"RA - Stem Cell Biology" 												
		+"RA - Synthetic Biology" 												
		+"RA - Toxicology" 														
		+"RA - Zoology" as total_RA_ct
	from(		
		select  "Email"
		,case when "RA - Agriculture" is null then 0 else 1 end "RA - Agriculture" 												
		,case when "RA - Analytical Chemistry" is null then 0 else 1 end "RA - Analytical Chemistry" 											
		,case when "RA - Anatomy" is null then 0 else 1 end "RA - Anatomy" 															
		,case when "RA - Biochemistry"  is null then 0 else 1 end "RA - Biochemistry" 													
		,case when "RA - Biodefense" is null then 0 else 1 end "RA - Biodefense" 													
		,case when "RA - Bioinformatics" is null then 0 else 1 end "RA - Bioinformatics"													
		,case when "RA - Biophysics" is null then 0 else 1 end "RA - Biophysics" 														
		,case when "RA - Bioprocessing" is null then 0 else 1 end "RA - Bioprocessing" 													
		,case when "RA - Biostatistics" is null then 0 else 1 end "RA - Biostatistics" 													
		,case when "RA - Botany" is null then 0 else 1 end "RA - Botany" 													
		,case when "RA - Cancer/Oncology" is null then 0 else 1 end "RA - Cancer/Oncology" 												
		,case when "RA - Cell Biology" is null then 0 else 1 end "RA - Cell Biology" 												
		,case when "RA - Clinical Diagnostics" is null then 0 else 1 end "RA - Clinical Diagnostics" 											
		,case when "RA - Developmental Biology" is null then 0 else 1 end "RA - Developmental Biology" 										
		,case when "RA - Drug Discovery/R&D" is null then 0 else 1 end "RA - Drug Discovery/R&D" 												
		,case when "RA - Environmental Science" is null then 0 else 1 end "RA - Environmental Science" 										
		,case when "RA - Epigenetics/Epigenomics" is null then 0 else 1 end "RA - Epigenetics/Epigenomics" 										
		,case when "RA - Food Science" is null then 0 else 1 end "RA - Food Science" 												
		,case when "RA - Forensics" is null then 0 else 1 end "RA - Forensics" 													
		,case when "RA - Gene Therapy" is null then 0 else 1 end "RA - Gene Therapy" 												
		,case when "RA - Genetics/Genomics" is null then 0 else 1 end "RA - Genetics/Genomics" 											
		,case when "RA - Hematology" is null then 0 else 1 end "RA - Hematology" 														
		,case when "RA - Histology" is null then 0 else 1 end "RA - Histology" 														
		,case when "RA - Immunology/Virology" is null then 0 else 1 end "RA - Immunology/Virology" 												
		,case when "RA - Material Sciences/Polymer Chemistry" is null then 0 else 1 end "RA - Material Sciences/Polymer Chemistry" 							
		,case when "RA - Medicinal Chemistry" is null then 0 else 1 end "RA - Medicinal Chemistry" 											
		,case when "RA - Microbiology" is null then 0 else 1 end "RA - Microbiology" 												
		,case when "RA - Molecular Biology" is null then 0 else 1 end "RA - Molecular Biology" 												
		,case when "RA - Molecular Diagnostics" is null then 0 else 1 end "RA - Molecular Diagnostics" 										
		,case when "RA - Nanotechnology" is null then 0 else 1 end "RA - Nanotechnology" 												
		,case when "RA - Neuroscience" is null then 0 else 1 end "RA - Neuroscience" 												
		,case when "RA - Organic Chemistry"  is null then 0 else 1 end "RA - Organic Chemistry" 											
		,case when "RA - Other (please specify)" is null then 0 else 1 end "RA - Other (please specify)" 											
		,case when "RA - Pathology" is null then 0 else 1 end "RA - Pathology" 														
		,case when "RA - Pharmacogenomics" is null then 0 else 1 end "RA - Pharmacogenomics" 												
		,case when "RA - Protein Sciences" is null then 0 else 1 end "RA - Protein Sciences" 												
		,case when "RA - Proteomics" is null then 0 else 1 end "RA - Proteomics" 														
		,case when "RA - Regenerative Medicine" is null then 0 else 1 end "RA - Regenerative Medicine"											
		,case when "RA - Stem Cell Biology" is null then 0 else 1 end "RA - Stem Cell Biology" 												
		,case when "RA - Synthetic Biology" is null then 0 else 1 end "RA - Synthetic Biology" 												
		,case when "RA - Toxicology" is null then 0 else 1 end "RA - Toxicology" 														
		,case when "RA - Zoology" is null then 0 else 1 end "RA - Zoology" 															
From sab_dir_raw_asci)a1) a2
group by 1
order by 1;