create table sab_ta_raw_asci_01042016_trimValues as(
select 
TRIM("15-102 IUPAC Scrape 6/22/15") as "15-102 IUPAC Scrape 6/22/15"
,TRIM("Account Notes") as "Account Notes"
,TRIM("account_status") as "account_status"
,TRIM("Address1") as "Address1"
,TRIM("Address2") as "Address2"
,TRIM("Admin Notes") as "Admin Notes"
,TRIM("Biopharmaceutical Drug Development Role - Assay Development") as "Biopharmaceutical Drug Development Role - Assay Development"
,TRIM("Biopharmaceutical Drug Development Role - Downstream ProcessDev") as "Biopharmaceutical Drug Development Role - Downstream ProcessDev"
,TRIM("Biopharmaceutical Drug Development Role - Formulation Dev") as "Biopharmaceutical Drug Development Role - Formulation Dev"
,TRIM("Biopharmaceutical Drug Development Role - Manufacturing") as "Biopharmaceutical Drug Development Role - Manufacturing"
,TRIM("Biopharmaceutical Drug Development Role - Other (specify)") as "Biopharmaceutical Drug Development Role - Other (specify)"
,TRIM("Biopharmaceutical Drug Development Role - Other") as "Biopharmaceutical Drug Development Role - Other"
,TRIM("Biopharmaceutical Drug Development Role - QA/QC") as "Biopharmaceutical Drug Development Role - QA/QC"
,TRIM("Biopharmaceutical Drug Development Role - Upstream Process Dev") as "Biopharmaceutical Drug Development Role - Upstream Process Dev"
,TRIM("Canc - Bladder") as "Canc - Bladder"
,TRIM("Canc - Brain") as "Canc - Brain"
,TRIM("Canc - Breast") as "Canc - Breast"
,TRIM("Canc - Cervical") as "Canc - Cervical"
,TRIM("Canc - CNS, not brain") as "Canc - CNS, not brain"
,TRIM("Canc - Colon/rectal") as "Canc - Colon/rectal"
,TRIM("Canc - Esophagus") as "Canc - Esophagus"
,TRIM("Canc - Kidney") as "Canc - Kidney"
,TRIM("Canc - Leukemia") as "Canc - Leukemia"
,TRIM("Canc - Liver") as "Canc - Liver"
,TRIM("Canc - Lung") as "Canc - Lung"
,TRIM("Canc - Lymphoma") as "Canc - Lymphoma"
,TRIM("Canc - Melanoma") as "Canc - Melanoma"
,TRIM("Canc - Neuroblastoma") as "Canc - Neuroblastoma"
,TRIM("Canc - Other (please specify)") as "Canc - Other (please specify)"
,TRIM("Canc - Other") as "Canc - Other"
,TRIM("Canc - Ovarian") as "Canc - Ovarian"
,TRIM("Canc - Pancreas") as "Canc - Pancreas"
,TRIM("Canc - Prostate") as "Canc - Prostate"
,TRIM("Canc - Uterine") as "Canc - Uterine"
,TRIM("CDD - Blood Bank") as "CDD - Blood Bank"
,TRIM("CDD - Clinical Chemistry") as "CDD - Clinical Chemistry"
,TRIM("CDD - Cytopathology") as "CDD - Cytopathology"
,TRIM("CDD - Diagnostic Imaging/Radiology") as "CDD - Diagnostic Imaging/Radiology"
,TRIM("CDD - Drug Testing") as "CDD - Drug Testing"
,TRIM("CDD - Hematology and Coagulation") as "CDD - Hematology and Coagulation"
,TRIM("CDD - Histopathology") as "CDD - Histopathology"
,TRIM("CDD - Immunology") as "CDD - Immunology"
,TRIM("CDD - Microbiology") as "CDD - Microbiology"
,TRIM("CDD - Molecular Diagnostics and Genetics (pharmageno,prenatal)") as "CDD - Molecular Diagnostics and Genetics (pharmageno,prenatal)"
,TRIM("CDD - Other (please specify)") as "CDD - Other (please specify)"
,TRIM("CDD - Other") as "CDD - Other"
,TRIM("CDD - Toxicology") as "CDD - Toxicology"
,TRIM("CDD - Urinalysis") as "CDD - Urinalysis"
,TRIM("Cert - Allergy and Immunology") as "Cert - Allergy and Immunology"
,TRIM("Cert - Anesthesiology") as "Cert - Anesthesiology"
,TRIM("Cert - Colon and Rectal Surgery") as "Cert - Colon and Rectal Surgery"
,TRIM("Cert - Dermatology") as "Cert - Dermatology"
,TRIM("Cert - Emergency Medicine") as "Cert - Emergency Medicine"
,TRIM("Cert - Family Medicine") as "Cert - Family Medicine"
,TRIM("Cert - I do not have any board certifications") as "Cert - I do not have any board certifications"
,TRIM("Cert - Internal Medicine") as "Cert - Internal Medicine"
,TRIM("Cert - Medical Genetics") as "Cert - Medical Genetics"
,TRIM("Cert - Neurological Surgery") as "Cert - Neurological Surgery"
,TRIM("Cert - Neurology") as "Cert - Neurology"
,TRIM("Cert - Nuclear Medicine") as "Cert - Nuclear Medicine"
,TRIM("Cert - Obstetrics and Gynecology") as "Cert - Obstetrics and Gynecology"
,TRIM("Cert - Ophthalmology") as "Cert - Ophthalmology"
,TRIM("Cert - Orthopaedic Surgery") as "Cert - Orthopaedic Surgery"
,TRIM("Cert - Other (please specify)") as "Cert - Other (please specify)"
,TRIM("Cert - Other") as "Cert - Other"
,TRIM("Cert - Otolaryngology") as "Cert - Otolaryngology"
,TRIM("Cert - Pathology") as "Cert - Pathology"
,TRIM("Cert - Pediatrics") as "Cert - Pediatrics"
,TRIM("Cert - Physical Medicine and Rehabilitation") as "Cert - Physical Medicine and Rehabilitation"
,TRIM("Cert - Plastic Surgery") as "Cert - Plastic Surgery"
,TRIM("Cert - Preventive Medicine") as "Cert - Preventive Medicine"
,TRIM("Cert - Psychiatry") as "Cert - Psychiatry"
,TRIM("Cert - Radiation Oncology") as "Cert - Radiation Oncology"
,TRIM("Cert - Radiology") as "Cert - Radiology"
,TRIM("Cert - Surgery") as "Cert - Surgery"
,TRIM("Cert - Thoracic Surgery") as "Cert - Thoracic Surgery"
,TRIM("Cert - Urology") as "Cert - Urology"
,TRIM("City") as "City"
,TRIM("Clinical Job Position - Other") as "Clinical Job Position - Other"
,TRIM("Clinical Job Position") as "Clinical Job Position"
,TRIM("Clinical Work Focus") as "Clinical Work Focus"
,TRIM("contact_hash") as "contact_hash"
,TRIM("ContactID") as "ContactID"
,TRIM("Continent") as "Continent"
,"Conversion to SAB"
,TRIM("Core") as "Core"
,TRIM("Country") as "Country"
,"CreationDate"
,TRIM("Customer List") as "Customer List"
,TRIM("Degree") as "Degree"
,TRIM("Department") as "Department"
,TRIM("Dis - Autoimmune disease") as "Dis - Autoimmune disease"
,TRIM("Dis - Cancer") as "Dis - Cancer"
,TRIM("Dis - Cardiovascular disease") as "Dis - Cardiovascular disease"
,TRIM("Dis - Diabetes") as "Dis - Diabetes"
,TRIM("Dis - Endocrine system disorders") as "Dis - Endocrine system disorders"
,TRIM("Dis - Infectious diseases") as "Dis - Infectious diseases"
,TRIM("Dis - Inflammation") as "Dis - Inflammation"
,TRIM("Dis - My work does not focus on any particular disease") as "Dis - My work does not focus on any particular disease"
,TRIM("Dis - Neurological disorders") as "Dis - Neurological disorders"
,TRIM("Dis - Other (please specify)") as "Dis - Other (please specify)"
,TRIM("Dis - Other") as "Dis - Other"
,TRIM("Email") as "Email"
,TRIM("Employment Sector - Other") as "Employment Sector - Other"
,TRIM("Employment Sector") as "Employment Sector"
,TRIM("ExternalDataReference") as "ExternalDataReference"
,TRIM("FirstName") as "FirstName"
,TRIM("Food/Beverage Science - Flavor Chemistry/Sensory Science") as "Food/Beverage Science - Flavor Chemistry/Sensory Science"
,TRIM("Food/Beverage Science - Food/Beverage Microbiology") as "Food/Beverage Science - Food/Beverage Microbiology"
,TRIM("Food/Beverage Science - Other (please specify)") as "Food/Beverage Science - Other (please specify)"
,TRIM("Food/Beverage Science - Other") as "Food/Beverage Science - Other"
,TRIM("Food/Beverage Science - Product R&D") as "Food/Beverage Science - Product R&D"
,TRIM("Food/Beverage Science - QA/QC") as "Food/Beverage Science - QA/QC"
,TRIM("Food/Beverage Science - Regulations/Compliance") as "Food/Beverage Science - Regulations/Compliance"
,TRIM("Food/Beverage Science - Research") as "Food/Beverage Science - Research"
,TRIM("ForenSci - Biological/Medical Examination") as "ForenSci - Biological/Medical Examination"
,TRIM("ForenSci - Physical Examinations") as "ForenSci - Physical Examinations"
,TRIM("Groups") as "Groups"
,TRIM("Job Position - Other") as "Job Position - Other"
,TRIM("Job Position") as "Job Position"
,TRIM("Laboratory Type") as "Laboratory Type"
,TRIM("Language") as "Language"
,"last_incidence_date"
,TRIM("LastName") as "LastName"
,TRIM("Legacy_PRDB") as "Legacy_PRDB"
,TRIM("Link/Search Terms") as "Link/Search Terms"
,TRIM("MissingInfo") as "MissingInfo"
,TRIM("Needs AutoConverted") as "Needs AutoConverted"
,TRIM("nonsab_points_option") as "nonsab_points_option"
,TRIM("Number of Beds") as "Number of Beds"
,TRIM("Organization") as "Organization"
,TRIM("Phone") as "Phone"
,TRIM("Phone_2") as "Phone_2"
,TRIM("Phone number") as "Phone number"
,TRIM("Points") as "Points"
,TRIM("PRID") as "PRID"
,TRIM("RA - Agriculture") as "RA - Agriculture"
,TRIM("RA - Analytical Chemistry") as "RA - Analytical Chemistry"
,TRIM("RA - Anatomy") as "RA - Anatomy"
,TRIM("RA - Biochemistry") as "RA - Biochemistry"
,TRIM("RA - Biodefense") as "RA - Biodefense"
,TRIM("RA - Bioinformatics") as "RA - Bioinformatics"
,TRIM("RA - Biophysics") as "RA - Biophysics"
,TRIM("RA - Bioprocessing") as "RA - Bioprocessing"
,TRIM("RA - Biostatistics") as "RA - Biostatistics"
,TRIM("RA - Botany") as "RA - Botany"
,TRIM("RA - Cancer/Oncology") as "RA - Cancer/Oncology"
,TRIM("RA - Cell Biology") as "RA - Cell Biology"
,TRIM("RA - Clinical Diagnostics") as "RA - Clinical Diagnostics"
,TRIM("RA - Developmental Biology") as "RA - Developmental Biology"
,TRIM("RA - Drug Discovery/R&D") as "RA - Drug Discovery/R&D"
,TRIM("RA - Environmental Science") as "RA - Environmental Science"
,TRIM("RA - Epigenetics/Epigenomics") as "RA - Epigenetics/Epigenomics"
,TRIM("RA - Food Science") as "RA - Food Science"
,TRIM("RA - Forensics") as "RA - Forensics"
,TRIM("RA - Gene Therapy") as "RA - Gene Therapy"
,TRIM("RA - Genetics/Genomics") as "RA - Genetics/Genomics"
,TRIM("RA - Hematology") as "RA - Hematology"
,TRIM("RA - Histology") as "RA - Histology"
,TRIM("RA - Immunology/Virology") as "RA - Immunology/Virology"
,TRIM("RA - Material Sciences/Polymer Chemistry") as "RA - Material Sciences/Polymer Chemistry"
,TRIM("RA - Material Sciences/Polymer Chemistry_2") as "RA - Material Sciences/Polymer Chemistry_2"
,TRIM("RA - Medicinal Chemistry") as "RA - Medicinal Chemistry"
,TRIM("RA - Microbiology") as "RA - Microbiology"
,TRIM("RA - Molecular Biology") as "RA - Molecular Biology"
,TRIM("RA - Molecular Diagnostics") as "RA - Molecular Diagnostics"
,TRIM("RA - Nanotechnology") as "RA - Nanotechnology"
,TRIM("RA - Neuroscience") as "RA - Neuroscience"
,TRIM("RA - Organic Chemistry") as "RA - Organic Chemistry"
,TRIM("RA - Other (please specify)") as "RA - Other (please specify)"
,TRIM("RA - Pathology") as "RA - Pathology"
,TRIM("RA - Pharmacogenomics") as "RA - Pharmacogenomics"
,TRIM("RA - Protein Sciences") as "RA - Protein Sciences"
,TRIM("RA - Proteomics") as "RA - Proteomics"
,TRIM("RA - Regenerative") as "RA - Regenerative"
,TRIM("RA - Regenerative Medicine") as "RA - Regenerative Medicine"
,TRIM("RA - Stem Cell Biology") as "RA - Stem Cell Biology"
,TRIM("RA - Synthetic Biology") as "RA - Synthetic Biology"
,TRIM("RA - Toxicology") as "RA - Toxicology"
,TRIM("RA - Zoology") as "RA - Zoology"
,TRIM("Recruitment Note") as "Recruitment Note"
,TRIM("Recruitment Notes") as "Recruitment Notes"
,TRIM("Recruitment Tag") as "Recruitment Tag"
,TRIM("ReferredByName") as "ReferredByName"
,TRIM("ReferredByPID") as "ReferredByPID"
,TRIM("RemoveTTs") as "RemoveTTs"
,TRIM("Research Areas - Other") as "Research Areas - Other"
,TRIM("Research/Work Focus") as "Research/Work Focus"
,TRIM("SAB Team") as "SAB Team"
,TRIM("Salutation") as "Salutation"
,TRIM("Scientific Discipline - Agriculture") as "Scientific Discipline - Agriculture"
,TRIM("Scientific Discipline - Chemistry") as "Scientific Discipline - Chemistry"
,TRIM("Scientific Discipline - Environmental Sciences") as "Scientific Discipline - Environmental Sciences"
,TRIM("Scientific Discipline - Food/Beverage") as "Scientific Discipline - Food/Beverage"
,TRIM("Scientific Discipline - Material Sciences") as "Scientific Discipline - Material Sciences"
,TRIM("Scientific Discipline - Nanotechnology") as "Scientific Discipline - Nanotechnology"
,TRIM("Scientific Discipline - Other (please specify)") as "Scientific Discipline - Other (please specify)"
,TRIM("Scientific Discipline - Other") as "Scientific Discipline - Other"
,TRIM("Scientific Discipline - Physical Sciences") as "Scientific Discipline - Physical Sciences"
,TRIM("SDI - Application Focus Other") as "SDI - Application Focus Other"
,TRIM("SDI - Application Focus") as "SDI - Application Focus"
,TRIM("SDI - Contact") as "SDI - Contact"
,TRIM("SDI - Food Survey") as "SDI - Food Survey"
,TRIM("SDI - Industry Other") as "SDI - Industry Other"
,TRIM("SDI - Industry") as "SDI - Industry"
,TRIM("SDI - Lab Function Other") as "SDI - Lab Function Other"
,TRIM("SDI - Lab Function") as "SDI - Lab Function"
,TRIM("SDI - Potential Duplicate") as "SDI - Potential Duplicate"
,TRIM("SDI - Reference ID") as "SDI - Reference ID"
,TRIM("SDI - Source") as "SDI - Source"
,TRIM("SDI Technologies - AA") as "SDI Technologies - AA"
,TRIM("SDI Technologies - Arc/Spark") as "SDI Technologies - Arc/Spark"
,TRIM("SDI Technologies - Bioinformatics and Cheminformatics") as "SDI Technologies - Bioinformatics and Cheminformatics"
,TRIM("SDI Technologies - Biological Safety Cabinets") as "SDI Technologies - Biological Safety Cabinets"
,TRIM("SDI Technologies - Calorimetry") as "SDI Technologies - Calorimetry"
,TRIM("SDI Technologies - Capillary electrophoresis") as "SDI Technologies - Capillary electrophoresis"
,TRIM("SDI Technologies - Centrifugation") as "SDI Technologies - Centrifugation"
,TRIM("SDI Technologies - Chemical Sensors") as "SDI Technologies - Chemical Sensors"
,TRIM("SDI Technologies - Color Measurement") as "SDI Technologies - Color Measurement"
,TRIM("SDI Technologies - Confocal Microscopy") as "SDI Technologies - Confocal Microscopy"
,TRIM("SDI Technologies - Continuous Flow Analysis and Discrete Analyz") as "SDI Technologies - Continuous Flow Analysis and Discrete Analyz"
,TRIM("SDI Technologies - Dissolution Testing") as "SDI Technologies - Dissolution Testing"
,TRIM("SDI Technologies - Electrochemistry") as "SDI Technologies - Electrochemistry"
,TRIM("SDI Technologies - Electron Microscopes") as "SDI Technologies - Electron Microscopes"
,TRIM("SDI Technologies - Electron Microscopy") as "SDI Technologies - Electron Microscopy"
,TRIM("SDI Technologies - Electrophoresis") as "SDI Technologies - Electrophoresis"
,TRIM("SDI Technologies - Electrophysiology/Patch Clamp") as "SDI Technologies - Electrophysiology/Patch Clamp"
,TRIM("SDI Technologies - ELISA") as "SDI Technologies - ELISA"
,TRIM("SDI Technologies - Ellipsometry") as "SDI Technologies - Ellipsometry"
,TRIM("SDI Technologies - ELN") as "SDI Technologies - ELN"
,TRIM("SDI Technologies - Extraction") as "SDI Technologies - Extraction"
,TRIM("SDI Technologies - Fermentors/Bioreactors") as "SDI Technologies - Fermentors/Bioreactors"
,TRIM("SDI Technologies - Flash Chromatography") as "SDI Technologies - Flash Chromatography"
,TRIM("SDI Technologies - Flow Cytometry") as "SDI Technologies - Flow Cytometry"
,TRIM("SDI Technologies - Fluorescence and Luminescence") as "SDI Technologies - Fluorescence and Luminescence"
,TRIM("SDI Technologies - FT-MS") as "SDI Technologies - FT-MS"
,TRIM("SDI Technologies - Fume Hoods") as "SDI Technologies - Fume Hoods"
,TRIM("SDI Technologies - Gas Chromatography") as "SDI Technologies - Gas Chromatography"
,TRIM("SDI Technologies - GC-MS") as "SDI Technologies - GC-MS"
,TRIM("SDI Technologies - GC") as "SDI Technologies - GC"
,TRIM("SDI Technologies - GC/MS") as "SDI Technologies - GC/MS"
,TRIM("SDI Technologies - HCS") as "SDI Technologies - HCS"
,TRIM("SDI Technologies - High Content Screening") as "SDI Technologies - High Content Screening"
,TRIM("SDI Technologies - HPLC") as "SDI Technologies - HPLC"
,TRIM("SDI Technologies - ICP-MS") as "SDI Technologies - ICP-MS"
,TRIM("SDI Technologies - ICP") as "SDI Technologies - ICP"
,TRIM("SDI Technologies - In Vivo Animal Imaging") as "SDI Technologies - In Vivo Animal Imaging"
,TRIM("SDI Technologies - Incubators") as "SDI Technologies - Incubators"
,TRIM("SDI Technologies - Infrared (IR)") as "SDI Technologies - Infrared (IR)"
,TRIM("SDI Technologies - Inorganic Elemental Analyzers") as "SDI Technologies - Inorganic Elemental Analyzers"
,TRIM("SDI Technologies - Ion Chromatography") as "SDI Technologies - Ion Chromatography"
,TRIM("SDI Technologies - Label-Free Detection/Biosensors") as "SDI Technologies - Label-Free Detection/Biosensors"
,TRIM("SDI Technologies - Laboratory Balances") as "SDI Technologies - Laboratory Balances"
,TRIM("SDI Technologies - Life Science Instrumentation") as "SDI Technologies - Life Science Instrumentation"
,TRIM("SDI Technologies - LIMS") as "SDI Technologies - LIMS"
,TRIM("SDI Technologies - Liquid Handling") as "SDI Technologies - Liquid Handling"
,TRIM("SDI Technologies - Low Pressure Liquid Chromatography") as "SDI Technologies - Low Pressure Liquid Chromatography"
,TRIM("SDI Technologies - Magnetic Sector") as "SDI Technologies - Magnetic Sector"
,TRIM("SDI Technologies - MALDI-TOF") as "SDI Technologies - MALDI-TOF"
,TRIM("SDI Technologies - Materials Characterization") as "SDI Technologies - Materials Characterization"
,TRIM("SDI Technologies - Microarrays") as "SDI Technologies - Microarrays"
,TRIM("SDI Technologies - Microplate Readers") as "SDI Technologies - Microplate Readers"
,TRIM("SDI Technologies - Microwave Assisted Chemistry") as "SDI Technologies - Microwave Assisted Chemistry"
,TRIM("SDI Technologies - Molecular Spectroscopy") as "SDI Technologies - Molecular Spectroscopy"
,TRIM("SDI Technologies - MS") as "SDI Technologies - MS"
,TRIM("SDI Technologies - Near Infrared (NIR)") as "SDI Technologies - Near Infrared (NIR)"
,TRIM("SDI Technologies - NMR") as "SDI Technologies - NMR"
,TRIM("SDI Technologies - Nucleic Acid Prep and Cell Separation") as "SDI Technologies - Nucleic Acid Prep and Cell Separation"
,TRIM("SDI Technologies - Optical Microscopy") as "SDI Technologies - Optical Microscopy"
,TRIM("SDI Technologies - Organic Elemental Analyzers") as "SDI Technologies - Organic Elemental Analyzers"
,TRIM("SDI Technologies - Particle Characterization") as "SDI Technologies - Particle Characterization"
,TRIM("SDI Technologies - Particle Size") as "SDI Technologies - Particle Size"
,TRIM("SDI Technologies - PCR") as "SDI Technologies - PCR"
,TRIM("SDI Technologies - Petroleum Analyzers") as "SDI Technologies - Petroleum Analyzers"
,TRIM("SDI Technologies - Physical Testing") as "SDI Technologies - Physical Testing"
,TRIM("SDI Technologies - Polarimetry/Refractometry") as "SDI Technologies - Polarimetry/Refractometry"
,TRIM("SDI Technologies - Portable and In-Field MS") as "SDI Technologies - Portable and In-Field MS"
,TRIM("SDI Technologies - Portable Instruments") as "SDI Technologies - Portable Instruments"
,TRIM("SDI Technologies - Process LC") as "SDI Technologies - Process LC"
,TRIM("SDI Technologies - Radioactivity") as "SDI Technologies - Radioactivity"
,TRIM("SDI Technologies - Raman") as "SDI Technologies - Raman"
,TRIM("SDI Technologies - Robotics") as "SDI Technologies - Robotics"
,TRIM("SDI Technologies - Scanning Probe Microscopy") as "SDI Technologies - Scanning Probe Microscopy"
,TRIM("SDI Technologies - SDMS") as "SDI Technologies - SDMS"
,TRIM("SDI Technologies - Sequencers") as "SDI Technologies - Sequencers"
,TRIM("SDI Technologies - Single Quadrupole LC/MS") as "SDI Technologies - Single Quadrupole LC/MS"
,TRIM("SDI Technologies - Surface Analyzers") as "SDI Technologies - Surface Analyzers"
,TRIM("SDI Technologies - Synthesizers") as "SDI Technologies - Synthesizers"
,TRIM("SDI Technologies - Tandem LC/MS") as "SDI Technologies - Tandem LC/MS"
,TRIM("SDI Technologies - Thermal Analysis") as "SDI Technologies - Thermal Analysis"
,TRIM("SDI Technologies - Thin Layer Chromatography") as "SDI Technologies - Thin Layer Chromatography"
,TRIM("SDI Technologies - Time of Flight LC-MS") as "SDI Technologies - Time of Flight LC-MS"
,TRIM("SDI Technologies - TOC and Other Sum Parameters") as "SDI Technologies - TOC and Other Sum Parameters"
,TRIM("SDI Technologies - Transfection") as "SDI Technologies - Transfection"
,TRIM("SDI Technologies - UV-Vis") as "SDI Technologies - UV-Vis"
,TRIM("SDI Technologies - Viscometry and Rheometry") as "SDI Technologies - Viscometry and Rheometry"
,TRIM("SDI Technologies - Xray") as "SDI Technologies - Xray"
,TRIM("SDI Technologies - XRD") as "SDI Technologies - XRD"
,TRIM("SDI Technologies - XRF") as "SDI Technologies - XRF"
,TRIM("SDI-TA Pre-existing") as "SDI-TA Pre-existing"
,TRIM("Segment") as "Segment"
,TRIM("State/Province") as "State/Province"
,TRIM("Street Address") as "Street Address"
,TRIM("Survey Response") as "Survey Response"
,TRIM("temp_project_flag") as "temp_project_flag"
,TRIM("temp_project_flag10") as "temp_project_flag10"
,TRIM("temp_project_flag2") as "temp_project_flag2"
,TRIM("temp_project_flag3") as "temp_project_flag3"
,TRIM("temp_project_flag4") as "temp_project_flag4"
,TRIM("temp_project_flag5") as "temp_project_flag5"
,TRIM("temp_project_flag6") as "temp_project_flag6"
,TRIM("temp_project_flag7") as "temp_project_flag7"
,TRIM("temp_project_flag8") as "temp_project_flag8"
,TRIM("Temp_project_flag9") as "Temp_project_flag9"
,TRIM("temp_project_flag9") as "temp_project_flag9"
,TRIM("temp_projectflag10") as "temp_projectflag10"
,TRIM("temp_projectflag3") as "temp_projectflag3"
,TRIM("temp_projectflag4") as "temp_projectflag4"
,TRIM("temp-tag-15-170") as "temp-tag-15-170"
,TRIM("ToM - Cell Based Therapies") as "ToM - Cell Based Therapies"
,TRIM("ToM - Monoclonal Antibodies (mAbs)") as "ToM - Monoclonal Antibodies (mAbs)"
,TRIM("ToM - Non-Antibody Protein Therapeutics") as "ToM - Non-Antibody Protein Therapeutics"
,TRIM("ToM - Nucleic Acid Based Therapeutics") as "ToM - Nucleic Acid Based Therapeutics"
,TRIM("ToM - Other (please specify)") as "ToM - Other (please specify)"
,TRIM("ToM - Other") as "ToM - Other"
,TRIM("ToM - Small Molecule Therapeutics") as "ToM - Small Molecule Therapeutics"
,TRIM("ToM - Vaccines") as "ToM - Vaccines"
,TRIM("Tools/Techniques - Other") as "Tools/Techniques - Other"
,TRIM("TT - 2-D Gel Electrophoresis") as "TT - 2-D Gel Electrophoresis"
,TRIM("TT - Bacteria Culture") as "TT - Bacteria Culture"
,TRIM("TT - Calorimetry (including ITC, DSC)") as "TT - Calorimetry (including ITC, DSC)"
,TRIM("TT - Cell-Based Assays") as "TT - Cell-Based Assays"
,TRIM("TT - Chromatography") as "TT - Chromatography"
,TRIM("TT - Classical End-Point PCR") as "TT - Classical End-Point PCR"
,TRIM("TT - Cloning/Molecular Biology Techniques") as "TT - Cloning/Molecular Biology Techniques"
,TRIM("TT - Confocal Microscopy") as "TT - Confocal Microscopy"
,TRIM("TT - DNA/RNA Microarrays") as "TT - DNA/RNA Microarrays"
,TRIM("TT - Enzyme-linked Immunosorbent Assay (ELISA)") as "TT - Enzyme-linked Immunosorbent Assay (ELISA)"
,TRIM("TT - Eukaryotic Cell/Tissue Culture") as "TT - Eukaryotic Cell/Tissue Culture"
,TRIM("TT - Flow Cytometry") as "TT - Flow Cytometry"
,TRIM("TT - Fluorescence Microscopy") as "TT - Fluorescence Microscopy"
,TRIM("TT - Gene Expression Analysis") as "TT - Gene Expression Analysis"
,TRIM("TT - Genotyping") as "TT - Genotyping"
,TRIM("TT - High Content Screening") as "TT - High Content Screening"
,TRIM("TT - High-Throughput Screening (HTS)") as "TT - High-Throughput Screening (HTS)"
,TRIM("TT - Immunohistochemistry") as "TT - Immunohistochemistry"
,TRIM("TT - Label-Free Detection/Analysis (Biosensors, SPR, etc.)") as "TT - Label-Free Detection/Analysis (Biosensors, SPR, etc.)"
,TRIM("TT - Light Microscopy") as "TT - Light Microscopy"
,TRIM("TT - Light Scattering (MALS, DLS)") as "TT - Light Scattering (MALS, DLS)"
,TRIM("TT - Mass Spectrometry") as "TT - Mass Spectrometry"
,TRIM("TT - Multiplex Bead Assays") as "TT - Multiplex Bead Assays"
,TRIM("TT - Next Generation Sequencing") as "TT - Next Generation Sequencing"
,TRIM("TT - Other Tools or Techniques (please specify)") as "TT - Other Tools or Techniques (please specify)"
,TRIM("TT - Protein Purification & Separation") as "TT - Protein Purification & Separation"
,TRIM("TT - Protein Structural Analysis (NMR, XRay Crystallography,CD)") as "TT - Protein Structural Analysis (NMR, XRay Crystallography,CD)"
,TRIM("TT - Real-Time PCR (including qPCR and RT-PCR)") as "TT - Real-Time PCR (including qPCR and RT-PCR)"
,TRIM("TT - RNAi (including siRNA, miRNA)") as "TT - RNAi (including siRNA, miRNA)"
,TRIM("TT - Sanger DNA Sequencing") as "TT - Sanger DNA Sequencing"
,TRIM("TT - Single Nucleotide Polymorphism (genotyping, discovery)") as "TT - Single Nucleotide Polymorphism (genotyping, discovery)"
,TRIM("TT - Stem Cell Culture/Analysis") as "TT - Stem Cell Culture/Analysis"
,TRIM("TT - Western Blotting") as "TT - Western Blotting"
,TRIM("TT - Chromatography_2") as "TT - Chromatography_2"
,TRIM("TT - Genotyping_2") as "TT - Genotyping_2"
,TRIM("TT - Immunohistochemistry_2") as "TT - Immunohistochemistry_2"
,TRIM("Unsubscribed") as "Unsubscribed"
,TRIM("UserType") as "UserType"
,TRIM("Zip Code") as "Zip Code"
,TRIM("Zip/Postal Code") as "Zip/Postal Code"
from sab_ta_raw_asci_01042016
)